version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run: yarn lint
  integration:
    docker:
      - image: circleci/node:14.6
    steps:
      - checkout
      - add_ssh_keys:
        fingerprints:
          - "52:e0:39:8d:60:44:db:eb:0c:01:d6:70:ea:4c:6c:13" # deploy key for core
      - run: git submodule sync
      - run: git submodule update --init
      - setup-remote-docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run: docker-compose -f docker-compose.yml -f docker-compose.openethereum.yml up
workflows:
  version: 2
  build_lint:
    jobs:
      - build
      - lint:
          requires:
            - build
      - integration:
          requires:
            - build
